name: "Terraform CI"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-south-1
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: "Terraform Init and Plan"
        run: |
          cd environments/dev/network
          terraform init
          terraform apply --auto-approve
          cd ../../../
          cd environments/dev/storage
          terraform init
          terraform plan
          cd ../../../
          cd environments/dev/compute
          terraform init
          terraform plan
          cd ../../../
          cd environments/dev/network
          terraform destroy --auto-approve
